on:
  release:
    types: [created]

jobs:
  releases:
    name: Release Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm64]
        exclude:
          - goos: darwin
            goarch: "386"
          - goos: windows
            goarch: arm64

    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.22
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "1.17"
          binary_name: "clang-tidy-cache"
